"""add users rules issues

Revision ID: f3ae71c83951
Revises: c7d3eec255a9
Create Date: 2026-10-06 15:06:36.033148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f3ae71c83951'
down_revision: Union[str, Sequence[str], None] = 'c7d3eec255a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('margin_left', sa.Float(), nullable=False),
    sa.Column('margin_right', sa.Float(), nullable=False),
    sa.Column('margin_top', sa.Float(), nullable=False),
    sa.Column('margin_bottom', sa.Float(), nullable=False),
    sa.Column('font_name', sa.String(), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('line_spacing', sa.Float(), nullable=False),
    sa.Column('first_line_indent', sa.Float(), nullable=False),
    sa.Column('heading_font_name', sa.String(), nullable=False),
    sa.Column('heading_font_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('expected', sa.String(), nullable=False),
    sa.Column('actual', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reports', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('rule_id', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('filename', sa.String(), nullable=False))
    report_status = postgresql.ENUM('UPLOADED', 'CHECKED', 'FIXED', 'FAILED', name='reportstatus', create_type=False)
    report_status.create(op.get_bind(), checkfirst=True)
    op.add_column('reports', sa.Column('status', report_status, nullable=False))
    op.add_column('reports', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key('fk_reports_rule_id_rules', 'reports', 'rules', ['rule_id'], ['id'])
    op.create_foreign_key('fk_reports_owner_id_users', 'reports', 'users', ['owner_id'], ['id'])
    op.drop_column('reports', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_reports_owner_id_users', 'reports', type_='foreignkey')
    op.drop_constraint('fk_reports_rule_id_rules', 'reports', type_='foreignkey')
    op.drop_column('reports', 'created_at')
    op.drop_column('reports', 'status')
    sa.Enum(name='reportstatus').drop(op.get_bind(), checkfirst=True)
    op.drop_column('reports', 'filename')
    op.drop_column('reports', 'rule_id')
    op.drop_column('reports', 'owner_id')
    op.drop_table('issues')
    op.drop_table('rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
